In [1]:
#importing required libraries
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt 
%matplotlib inline

from sklearn.metrics import mean_squared_log_error
from math import sqrt
from statistics import mean, stdev

import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv("ailerons_train.csv")

In [3]:
df.head()

,climbRate,Sgz,p,q,curPitch,curRoll,absRoll,diffClb,diffRollRate,diffDiffClb,...,diffSeTime8,diffSeTime9,diffSeTime10,diffSeTime11,diffSeTime12,diffSeTime13,diffSeTime14,alpha,Se,goal
0,2,-56,-0.33,-0.09,0.90,0.2,-11,12,0.004,-0.1,...,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.9,0.032,-0.0009
1,470,-39,0.02,0.12,0.39,-0.6,-12,8,0.009,-1.6,...,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.9,0.034,-0.0011
2,165,4,0.14,0.14,0.78,0.4,-11,-9,-0.003,-0.2,...,0.0,0.0,0.0,0.0,0.0,0.000,0.0,1.0,0.034,-0.0012
3,-113,5,-0.12,0.11,1.06,0.6,-10,-7,-0.008,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.9,0.033,-0.0011
4,-411,-21,-0.17,0.07,1.33,-0.6,-11,0,0.002,0.1,...,0.0,0.0,0.0,0.0,0.0,-0.002,0.0,0.9,0.032,-0.0008

In [4]:
df.shape

(12250, 41)

In [5]:
df.describe()

,climbRate,Sgz,p,q,curPitch,curRoll,absRoll,diffClb,diffRollRate,diffDiffClb,...,diffSeTime8,diffSeTime9,diffSeTime10,diffSeTime11,diffSeTime12,diffSeTime13,diffSeTime14,alpha,Se,goal
count,12250.000000,12250.000000,12250.000000,12250.000000,12250.000000,12250.000000,12250.000000,12250.000000,12250.000000,12250.000000,...,12250.000000,12250.000000,1.225000e+04,12250.000000,1.225000e+04,12250.000000,1.225000e+04,12250.000000,12250.000000,12250.000000
mean,-9.362939,-12.632408,0.006878,0.061144,0.626213,0.067045,-11.068816,-0.919592,-0.000970,-0.053698,...,0.000000,-0.000103,-5.714286e-07,-0.000100,-6.530612e-07,-0.000096,-3.265306e-07,0.622106,0.021949,-0.000871
std,259.502687,25.727234,0.305488,0.118447,0.312061,0.969050,4.094653,10.405533,0.013352,1.121631,...,0.000013,0.000621,8.806480e-05,0.000644,5.569441e-05,0.000617,3.129801e-05,0.195486,0.006912,0.000404
min,-975.000000,-99.000000,-1.530000,-0.540000,-0.420000,-3.100000,-23.000000,-43.000000,-0.099000,-8.800000,...,-0.001000,-0.006000,-6.000000e-03,-0.006000,-4.000000e-03,-0.006000,-3.000000e-03,0.400000,0.012000,-0.003600
25%,-176.000000,-29.000000,-0.220000,-0.020000,0.420000,-0.600000,-14.000000,-8.000000,-0.009000,-0.300000,...,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.500000,0.018000,-0.001100
50%,-20.000000,-13.000000,0.020000,0.060000,0.610000,0.200000,-11.000000,-1.000000,-0.001000,-0.100000,...,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.600000,0.020000,-0.000800
75%,159.000000,3.000000,0.230000,0.130000,0.800000,0.700000,-8.000000,6.000000,0.008000,0.200000,...,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.700000,0.023000,-0.000600
max,977.000000,94.000000,1.060000,0.620000,2.580000,2.900000,-3.000000,46.000000,0.056000,11.200000,...,0.001000,0.003000,6.000000e-03,0.005000,2.000000e-03,0.007000,1.000000e-03,2.000000,0.073000,-0.000200

In [6]:
def checkna(columns):
    for i in columns:
        print(i," ",((df[i].isna().sum()/len(df[i]))*100))

In [7]:
checkna(df.columns)

climbRate   0.0
Sgz   0.0
p   0.0
q   0.0
curPitch   0.0
curRoll   0.0
absRoll   0.0
diffClb   0.0
diffRollRate   0.0
diffDiffClb   0.0
SeTime1   0.0
SeTime2   0.0
SeTime3   0.0
SeTime4   0.0
SeTime5   0.0
SeTime6   0.0
SeTime7   0.0
SeTime8   0.0
SeTime9   0.0
SeTime10   0.0
SeTime11   0.0
SeTime12   0.0
SeTime13   0.0
SeTime14   0.0
diffSeTime1   0.0
diffSeTime2   0.0
diffSeTime3   0.0
diffSeTime4   0.0
diffSeTime5   0.0
diffSeTime6   0.0
diffSeTime7   0.0
diffSeTime8   0.0
diffSeTime9   0.0
diffSeTime10   0.0
diffSeTime11   0.0
diffSeTime12   0.0
diffSeTime13   0.0
diffSeTime14   0.0
alpha   0.0
Se   0.0
goal   0.0

In [10]:
def outlierdetect(columns):
    for i in columns:
        print("Column is : ",i)
        IQR = (np.percentile(df[i], 75)) - (np.percentile(df[i], 25))
        whisker_val = (np.percentile(df[i], 75)) + (1.5*(IQR))
        print(df.loc[df[i]>whisker_val].shape)
        print("================")

In [12]:
i='climbRate'
IQR = (np.percentile(df[i], 75)) - (np.percentile(df[i], 25))
whisker_val = (np.percentile(df[i], 75)) + (1.5*(IQR))
df.loc[df[i]>whisker_val].shape

(81, 41)